plugins {
    id 'com.android.application'
}

android {
    namespace 'padik.deadreckoning'
    compileSdk 34

    defaultConfig {
        applicationId "padik.deadreckoning"
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.fragment:fragment:1.8.2'
    
    // OSMDroid
    implementation 'org.osmdroid:osmdroid-android:6.1.20'
    
    // Play Services Location
    implementation 'com.google.android.gms:play-services-location:21.4.0'
    
    // AChartEngine - Using JitPack mirror
    implementation 'com.github.ddanny:achartengine:master-SNAPSHOT'

    // EJML
    implementation 'org.ejml:ejml-all:0.41'

    // Gson
    implementation 'com.google.code.gson:gson:2.11.0'

    // TensorFlow Lite
    implementation 'org.tensorflow:tensorflow-lite:2.17.0'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}
